title: Richa Khagwal- Aspiring Data Scientist # your name (or website title) here
logo: "/images/pic.jpg.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/richa-khagwal-903474172/">LinkedIn</a> 
  <a href="https://github.com/rickhagwal">Github</a> 
  <a href="https://www.kaggle.com/rickhagwal5">Kaggle</a>
  <a href="https://twitter.com/Richa61042835">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
